TreeStructure/TreeStructure/Entities/Tree.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TreeStructure.Entities
{
    public class Tree
    {
        public int TreeId { get; set; }
        public string Name { get; set; }
        public int? ParentId { get; set; }

        public Tree()
        {
            
        }
        public Tree(int treeId,string name,int? parentId)
        {
            TreeId = treeId;
            Name = name;
            ParentId = parentId;
        }

        public Tree(string name,int? parentId) 
        {
            Name = name;
            ParentId = parentId;
        }

        
    }
}

TreeStructure/TreeStructure/Entities/TreeNode.cs
using System.ComponentModel.DataAnnotations;

namespace TreeStructure.Entities
{
    public class TreeNode
    {
        [Required]
        public string NodeType { get; set; }
        [Required]
        public string NodeName { get; set; }
        [Required]
        public int? ParentId { get; set; }
    }
}

TreeStructure/TreeStructure/Models/ErrorViewModel.cs
namespace TreeStructure.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TreeStructure/TreeStructure/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TreeStructure.Models;

namespace TreeStructure.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TreeStructure/TreeStructure/Controllers/TreeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks.Dataflow;
using System.Xml.Linq;
using TreeStructure.DAL;
using TreeStructure.Entities;
using TreeStructure.Models;

namespace TreeStructure.Controllers
{
    public class TreeController : Controller
    {
        private readonly TreeDbContext _dbContext;
        public TreeController(TreeDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        
        public ActionResult Index(string sortOrder)
        {
            List<Tree> treeList = new();
            treeList = _dbContext.Trees.OrderBy(x => x.TreeId).ToList();
            ViewBag.IdSort = String.IsNullOrEmpty(sortOrder) ? "Id_desc" : "";
            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            switch (sortOrder)
            {
                case "Id_desc":
                    treeList = treeList.OrderByDescending(x => x.TreeId).ToList();
                    break;
                case "name_desc":
                    treeList = treeList.OrderByDescending(x => x.Name).ToList();
                    break;
                default:
                    treeList = treeList.OrderBy(x => x.Name).ToList();
                    break;
            }
            return View(treeList);
        }

        [HttpGet]
        public ActionResult CreateTreeNode()
        {
            DropDownList();
            return View();
        }
        [HttpPost]
        public ActionResult CreateTreeNode(Tree tree) 
        {
            _dbContext.Trees.Add(tree);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("Tree/{treeId}/Delete")]
        public ActionResult DeleteTreeNode(int treeId)
        {
            var tree = _dbContext.Trees.FirstOrDefault(t => t.TreeId == treeId);
            return View(tree);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Tree/{treeId}/Delete")]
        public ActionResult DeleteTreeNode(Tree tree)
        {
            _dbContext.Trees.Remove(tree);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult ChangeNodePanel(string sortOrder)
        {
            List<Tree> treeList = new();
            treeList = _dbContext.Trees.ToList();
            ViewBag.ParentSort = String.IsNullOrEmpty(sortOrder) ? "parentId_desc" : "";
            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            switch(sortOrder)
            {
                case "parentId_desc":
                    treeList = treeList.OrderByDescending(x => x.ParentId).ToList();
                    break;
                case "name_desc":
                    treeList = treeList.OrderByDescending(x => x.Name).ToList();
                    break;
                default:
                    treeList = treeList.OrderBy(x => x.ParentId).ToList();
                    break;
            }
            return View(treeList);
        }

        [HttpGet]
        [Route("Tree/{treeId}/Edit")]
        public IActionResult EditTreeNode(int treeId)
        {
            var tree = _dbContext.Trees.FirstOrDefault(t => t.TreeId == treeId);
            DropDownList();
            return View(tree);
        }

        [HttpPost]
        [Route("Tree/{treeId}/Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditTreeNode(Tree tree)
        {
            if(ModelState.IsValid)
            {
                var entry = _dbContext.Entry(tree);
                entry.State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(tree);
        }

        private void DropDownList()
        {
            List<SelectListItem> nodes = new SelectList(_dbContext.Trees,"TreeId","Name").ToList();
            ViewBag.Nodes = nodes;
        }
    }
}

TreeStructure/TreeStructure/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TreeStructure/TreeStructure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TreeStructure</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TreeStructure.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TreeStructure</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tree" asp-action="Index">Tree Structure</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TreeStructure - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TreeStructure/TreeStructure/Views/Tree/ChangeNodePanel.cshtml
@model IEnumerable<TreeStructure.Entities.Tree>

@{
    ViewData["Title"] = "ChangeNodePanel";
}

<h1>Change Node Panel</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Name", "ChangeNodePanel", new { sortOrder = ViewBag.NameSort })
            </th>
            <th>
                @Html.ActionLink("ParentId", "ChangeNodePanel", new { sortOrder = ViewBag.ParentSort })
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParentId)
            </td>
            <td>
                  <a class="btn btn-warning" asp-controller="Tree" asp-action="EditTreeNode" asp-route-treeId="@item.TreeId">Edit</a>
                  <a class="btn btn-danger" asp-controller="Tree" asp-action="DeleteTreeNode" asp-route-treeId="@item.TreeId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

TreeStructure/TreeStructure/Views/Tree/CreateTreeNode.cshtml
@model TreeStructure.Entities.Tree

@{
    ViewData["Title"] = "CreateTreeNode";
}

<h1>CreateTreeNode</h1>

@using (Html.BeginForm("CreateTreeNode","Tree", FormMethod.Post)) {
<h4>Tree</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateTreeNode">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
               @Html.DropDownListFor(x => x.ParentId, (IEnumerable<SelectListItem>)ViewBag.Nodes,"Select Parent", new {@class = "form-control"})
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
}

<div>
    <a asp-action="Index" class="btn btn-success">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TreeStructure/TreeStructure/Views/Tree/DeleteTreeNode.cshtml
@model TreeStructure.Entities.Tree

@{
    ViewData["Title"] = "DeleteTreeNode";
}

<h1>DeleteTreeNode</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tree</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TreeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TreeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentId)
        </dd>
    </dl>
    
    <form asp-action="DeleteTreeNode">
        <input type="hidden" asp-for="TreeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </form>
</div>

TreeStructure/TreeStructure/Views/Tree/EditTreeNode.cshtml
@model TreeStructure.Entities.Tree

@{
    ViewData["Title"] = "EditTreeNode";
}

<h1>EditTreeNode</h1>

<h4>Tree</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditTreeNode">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TreeId" />
            <div class="form-group mb-3">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="ParentId" class="control-label"></label>
                <input asp-for="ParentId" class="form-control" />
                <span asp-validation-for="ParentId" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TreeStructure/TreeStructure/Views/Tree/Index.cshtml
@model IEnumerable<TreeStructure.Entities.Tree>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <a class="btn btn-success" asp-controller="Tree" asp-action="CreateTreeNode">Add New Tree Node</a>
    <br />
    <br />
    <a class="btn btn-danger" asp-controller="Tree" asp-action="ChangeNodePanel">Delete Tree Node</a>
    <br />
    <br />
    <a class="btn btn-warning" asp-controller="Tree" asp-action="ChangeNodePanel">Change Tree Node</a>
    <br />
    <br />
    @Html.Partial("Tree")
</div>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/lib/jquery/dist/jquery.js"stylesheet" />
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">


<style>
    .container {
        min-width: 500px;
        overflow: hidden;
    }

    .innerTable table {
        margin: 0px auto;
        border-left-width: 4px;
    }

    td.innerTable {
        padding-left: 20px;
    }

    .icon {
        background-repeat: no-repeat;
        width: 16px;
        height: 16px;
        display: inline-block;
        float: left;
    }

    .icon-e {
        background-position: -32px -16px;
    }

    .icon-s {
        background-position: -64px -16px;
    }
</style>

@section Scripts {
<script type="text/javascript">
    $(document).ready(function () {
        $('.icon').live('click', function () {
            var $pRow = $(this).parents('tr');
            var $nextRow = $pRow.next('tr');
            $nextRow.toggle();
            $(this).toggleClass('icon icon-e');
        });
    })
</script>
}

TreeStructure/TreeStructure/Views/Tree/Tree.cshtml
@using TreeStructure.Entities;
@model List<TreeStructure.Entities.Tree>

<table class="table table-bordered">
    @{
        int id = 0;
        int row = 0;
        int parentId = 0;
        foreach(var i in Model.Where(x => x.ParentId is null))
        {
            if(i.TreeId == id)
            {
                continue;
            }
            else
            {
                if(row == 0)
                {
                    <thead>
                        <tr>
                            <th>@Html.ActionLink("TreeId", "Index", new { sortOrder = ViewBag.IdSort })</th>
                            <th>@Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSort })</th>
                        </tr>
                    </thead>
                }
                row++;
                id = i.TreeId;
                var trees = Model.Where(x => x.ParentId.Equals(i.TreeId)).ToList();
                var newTreeList = Model.Where(x => !x.TreeId.Equals(x.TreeId)).ToList();
                <tbody>
                    <tr>
                        <td>
                        @if (trees.Count > 0)
                        {
                        <span class="icon icon-e" style="float:left; cursor:pointer;"><i class="bi bi-arrow-right"></i></span>
                        }
                        else
                        {
                        <span style="display:inline-block;width:14px">&nbsp;</span>
                        }
                        @i.TreeId</td>
                        <td>@i.Name</td>
                    </tr>
                </tbody>
            }
        }
    }
</table>